### ISSUE TITLE
Ultimine kicking out of server

### ISSUE THREAD

**Issue by Wolfbane319** [FTBTeam/FTB-Ultimine#14]
java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.func_174824_e(F)Lnet/minecraft/util/math/Vec3d;
at com.feed_the_beast.mods.ftbultimine.FTBUltimine.rayTrace(FTBUltimine.java:159)
at com.feed_the_beast.mods.ftbultimine.FTBUltimine.blockBroken(FTBUltimine.java:210)

Anytime I try to use Ultimine it kicks me out of the server and I have to restart it

**Comment by DroppedHeart** [comment]
#15 same issue
I'm also having this issue. Really annoying on an SMP with friends, would love an update on this.
